services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: customer-tracker-backend-dev
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///app/data/customer_tracker.db
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-here-change-in-production-min-256-bits}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
    volumes:
      - backend_data:/app/data
    ports:
      - "3000:3000"  # 开发环境保留后端端口用于直接访问
    networks:
      - customer-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 前端服务 (包含nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # 前端不再需要构建时环境变量
    container_name: customer-tracker-frontend-dev
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - customer-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 持久化存储
volumes:
  backend_data:
    driver: local

# 网络配置
networks:
  customer-tracker-network:
    driver: bridge