services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: customer-tracker-backend-prod
    restart: always
    environment:
      - DATABASE_URL=sqlite:///app/data/customer_tracker.db
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
    volumes:
      - backend_data:/app/data
    networks:
      - customer-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # 前端服务 (包含nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # 前端不再需要构建时环境变量
    container_name: customer-tracker-frontend-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - customer-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

# 持久化存储
volumes:
  backend_data:
    driver: local

# 网络配置
networks:
  customer-tracker-network:
    driver: bridge