version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: customer-tracker-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///app/data/customer_tracker.db
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-here-change-in-production-min-256-bits}
      - JWT_EXPIRE_HOURS=24
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - RUST_LOG=info
      - CORS_ORIGIN=http://localhost
    volumes:
      - backend_data:/app/data
    ports:
      - "3000:3000"
    networks:
      - customer-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
    container_name: customer-tracker-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - customer-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 持久化存储
volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

# 网络配置
networks:
  customer-tracker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16